DROP TABLE IF EXISTS COUNTRY_TAB;
 
CREATE TABLE COUNTRY_TAB(
  POPULATION INT  PRIMARY KEY,
  COUNTRY_NAME VARCHAR(250) NOT NULL,
  CAPITAL VARCHAR(250) NOT NULL,
  currency VARCHAR(250) DEFAULT NULL
);